apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vsp-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
