version: '3'

run: when_changed

env:
  CGO_ENABLED: "0"
  GOARCH:   '{{ default "amd64" .GOARCH }}'
  GOOS:     '{{ default "linux" .GOOS }}'
  SUBMODULES: '{{ default "true" .SUBMODULES }}'

vars:
  DPU_OPERATOR_TEMP_DIR: /tmp/dpu-operator-tmp
  DPU_OPERATOR_GO_CACHE: /tmp/dpu-operator-cache
  BINDIR: bin
  BINDIR_ABS:
    sh: if [[ "{{.BINDIR}}" = /* ]]; then echo "{{.BINDIR}}"; else echo "$(pwd)/{{.BINDIR}}"; fi
  REGISTRY:
    sh: hostname | sed 's/$/:5000/'
  ENVTEST_K8S_VERSION: 1.27.1
  KUSTOMIZE_VERSION: v5.6.0
  GINKGO_VERSION:
    sh: go list -m -f '{{"{{.Version}}"}}' github.com/onsi/ginkgo/v2 | sed 's/^v//'
  CONTROLLER_TOOLS_VERSION: v0.19.0
  SETUP_ENVTEST_VERSION: release-0.16
  OPERATOR_SDK_VERSION: v1.41.0
  OPM_VERSION: v1.23.0
  KUBECONFIG_HOST: "/root/kubeconfig.ocpcluster"
  KUBECONFIG_DPU: "/root/kubeconfig.microshift"

includes:
  images:
    taskfile: ./taskfiles/images.yaml
    flatten: true
  binaries:
    taskfile: ./taskfiles/binaries.yaml
    flatten: true
  clusters:
    taskfile: ./taskfiles/clusters.yaml
    flatten: true
  operator-sdk:
    taskfile: ./taskfiles/operator-sdk.yaml
    flatten: true
  proto:
    taskfile: ./taskfiles/proto.yaml
    flatten: true
  check:
    taskfile: ./taskfiles/check.yaml
    flatten: true
  
tasks:
  bindir:
    silent: true
    cmds:
      - echo "{{.BINDIR_ABS}}"

  push-image-helper:
    internal: true
    vars:
      SOURCE: '{{.SOURCE}}'
      IMAGE: '{{.IMAGE}}'
    cmds:
      - buildah manifest push --all '{{.SOURCE}}-manifest' 'docker://{{.IMAGE}}'

  undeploy-helper:
    internal: true
    deps:
      - task: kustomize
    vars:
      KUBECONFIG: '{{.KUBECONFIG}}'
    status:
      - NS=$(KUBECONFIG={{.KUBECONFIG}} oc get ns openshift-dpu-operator)
        if [[ -n "$NS" ]]; then false else true fi
    cmds:
      # this will block untill everything is cleaned up and bringing system back into a clean state as if the operator was never installed
      - KUBECONFIG={{.KUBECONFIG}} oc delete -f examples/config.yaml || true
      - bin/kustomize build config/default | KUBECONFIG={{.KUBECONFIG}} oc delete --ignore-not-found=true -f -
      - KUBECONFIG={{.KUBECONFIG}} oc wait --for=delete ns openshift-dpu-operator --timeout=300s
      - echo "Namespace 'openshift-dpu-operator' has been removed."

  undeploy:
    deps:
      - task: undeploy-helper
        vars:
          KUBECONFIG: '{{.KUBECONFIG_DPU}}'
      - task: undeploy-helper
        vars:
          KUBECONFIG: '{{.KUBECONFIG_HOST}}'

  undeploy-1c:
    deps:
      - task: undeploy-helper
        vars:
          KUBECONFIG: '{{.KUBECONFIG_HOST}}'

  deploy-prep:
    internal: true
    deps:
      - task: kustomize
    cmds:
      - >
        go run ./tools/config/config.go
        -registry-url {{.REGISTRY}}
        -template-file config/dev/local-images-template.yaml
        -output-file bin/local-images.yaml
      - cp config/dev/kustomization.yaml bin
  
  ## Download envtest-setup locally if necessary
  envtest:
    status:
      - test -s {{.BINDIR}}/setup-envtest
      - ./{{.BINDIR}}/setup-envtest --help | head -1 | grep -q {{.SETUP_ENVTEST_VERSION}}
    cmds:
      - GOBIN={{.BINDIR_ABS}} GOFLAGS='' go install sigs.k8s.io/controller-runtime/tools/setup-envtest@{{.SETUP_ENVTEST_VERSION}}

  deploy:
    deps:
      - task: deploy-prep
    cmds:
      - task: undeploy
        vars:
          KUBECONFIG_DPU: "{{.KUBECONFIG_DPU}}"
          KUBECONFIG_HOST: "{{.KUBECONFIG_HOST}}"
      - bin/kustomize build bin | KUBECONFIG="{{.KUBECONFIG_DPU}}" oc apply -f -
      - bin/kustomize build bin | KUBECONFIG="{{.KUBECONFIG_HOST}}" oc apply -f -
      - KUBECONFIG="{{.KUBECONFIG_DPU}}" oc -n openshift-dpu-operator wait --for=condition=ready pod --all --timeout=300s
      - KUBECONFIG="{{.KUBECONFIG_HOST}}" oc -n openshift-dpu-operator wait --for=condition=ready pod --all --timeout=300s

  deploy-1c:
    deps:
      - task: deploy-prep
    cmds:
      - task: undeploy-1c
        vars:
          KUBECONFIG_HOST: "{{.KUBECONFIG_HOST}}"
      - bin/kustomize build bin | KUBECONFIG="{{.KUBECONFIG_HOST}}" oc apply -f -
      - KUBECONFIG="{{.KUBECONFIG_HOST}}" oc -n openshift-dpu-operator wait --for=condition=ready pod --all --timeout=300s

  prepare-e2e-test:
    cmds:
      - >
        if [ "{{.SUBMODULES}}" = "true" ]; then
            hack/prepare-submodules.sh
        fi
            hack/prepare-venv.sh

  e2e-test:
    deps:
      - task: kustomize
    cmds:
      - task: deploy-2-clusters
      - task: fast-e2e-test

  e2e-test-1-cluster:
    deps:
      - task: kustomize
    cmds:
      - task: deploy-1-cluster
      - task: fast-e2e-test

  fast-e2e-test:
    cmds:
      - task: redeploy
      - KUBECONFIG_HOST={{.KUBECONFIG_HOST}} KUBECONFIG_DPU={{.KUBECONFIG_DPU}} sh hack/setup.sh
      - task: run-e2e-test

  run-e2e-test:
    deps:
      - task: ginkgo
      - task: envtest
    cmds:
      - >
        FAST_TEST=true
        REGISTRY={{.REGISTRY}}
        NF_INGRESS_IP=10.20.30.2
        EXTERNAL_CLIENT_DEV=eno12409
        EXTERNAL_CLIENT_IP=10.20.30.100
        KUBEBUILDER_ASSETS="$({{.BINDIR}}/setup-envtest use {{.ENVTEST_K8S_VERSION}} --bin-dir {{.BINDIR_ABS}} -p path)"
        {{.BINDIR}}/ginkgo -coverprofile cover.out ./e2e_test/...
      - hack/traffic_flow_tests.sh

  prepare-e2e-test:
    cmds:
      - >
        if [ "{{.SUBMODULES}}" = "true" ]; then
            hack/prepare-submodules.sh
        fi
            hack/prepare-venv.sh

  redeploy:
    cmds:
      - task: build-image-all
      - task: undeploy
      - task: deploy

  ## Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
  manifests:
    deps:
      - task: controller-gen
    cmds:
      - GOFLAGS='' {{.BINDIR}}/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases

  bundle:
    deps:
      - task: manifests
      - task: kustomize
      - task: operator-sdk
    cmds:
      - "{{.BINDIR}}/operator-sdk generate kustomize manifests -q"
      - cd config/manager && ../../{{.BINDIR}}/kustomize edit set image controller=${IMG:-controller:latest}
      - "{{.BINDIR}}/kustomize build config/manifests | {{.BINDIR}}/operator-sdk generate bundle -q --overwrite --version ${VERSION:-4.20.0}"
      - "{{.BINDIR}}/operator-sdk bundle validate ./bundle"
      - cp bundle/manifests/* manifests/stable

  ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
  generate:
    deps:
      - task: controller-gen
    cmds:
      - GOFLAGS='' {{.BINDIR}}/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."

  fmt:
    status:
      - |
        files=$(find . -name "*.go" -not -path "./vendor/*" -not -path "./dpu-api/vendor/*")
        output=$(gofmt -d $files)
        [ -z "$output" ]
    cmds:
      - go fmt ./...
      - cd api && go fmt ./...

  vet:
    cmds:
      - go vet ./...

  ## Download controller-gen locally if necessary. If wrong version is installed, it will be overwritten.
  controller-gen:
    status:
      - test -s {{.BINDIR}}/controller-gen
      - ./{{.BINDIR}}/controller-gen --version | grep -q {{.CONTROLLER_TOOLS_VERSION}}
    cmds:
      - GOBIN={{.BINDIR_ABS}} GOFLAGS='' go install sigs.k8s.io/controller-tools/cmd/controller-gen@{{.CONTROLLER_TOOLS_VERSION}}

  test:
    deps:
      - task: podman-check
      - task: manifests
      - task: generate
      - task: fmt
      - task: vet
      - task: envtest
      - task: ginkgo
    cmds:
      - >
        FAST_TEST=false
        KUBEBUILDER_ASSETS="$({{.BINDIR}}/setup-envtest use {{.ENVTEST_K8S_VERSION}} --bin-dir {{.BINDIR_ABS}} -p path)"
        timeout 30m {{.BINDIR}}/ginkgo --repeat 4 {{if .TEST_FOCUS}}-focus "{{.TEST_FOCUS}}" {{end}}-coverprofile cover.out ./internal/... ./pkgs/... ./api/v1/...

  fast-test:
    deps:
      - task: envtest
      - task: ginkgo
    cmds:
      - >
        FAST_TEST=true
        KUBEBUILDER_ASSETS="$({{.BINDIR}}/setup-envtest use {{.ENVTEST_K8S_VERSION}} --bin-dir {{.BINDIR_ABS}} -p path)"
        {{.BINDIR}}/ginkgo {{if .TEST_FOCUS}}-focus "{{.TEST_FOCUS}}" {{end}}-coverprofile cover.out ./internal/... ./pkgs/... ./api/v1/...

  vendor:
    cmds:
      - |
        for d in . dpu-api api tools ; do
          if [ "$d" = . ] ; then
            (cd "$d" && go mod vendor) || exit $? ;
          fi ;
          (cd "$d" && go mod tidy) || exit $? ;
        done
